### PR TITLE
replace request with got

### PR DESCRIPTION
**Pull request by yaniv-li**

### CODE REVIEW

**Comment by mikeys** [comment]
@yaniv-li Looks good, if we're doing this nice refactoring to `async/await`, is there any reason to keep callbacks at all? (e.g here: https://github.com/cloudinary/web-speed-test-server/pull/30/files#diff-bd578f88d2559b9591733a2a609ebacfb70efa8f49a63e00a03a2117308c5e10R20)

**Comment by yaniv-li** [comment]
@mikeys the only reason to keep it like that is that it would require a big refactor to all code (it is probably needed) and I don't know if now is the time for it (up to you).
I used `async/await` just because `got` does not support callbacks

**Comment by mikeys** [comment]
@yaniv-li whatever you decide for now is ok with me, although it's not a huge project.

**Comment by yaniv-li** [comment]
@mikeys I don't think we should do that now when we are just about to finish the first stage, probably it would be best to do that in the next stage.
if could approve this PR I'll merge it so you could deploy it to staging

**Review by mikeys — APPROVED** [review]

**Pull request merged**
